/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RhymingDictionary;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alain
 */
public class RhymingDictionary extends javax.swing.JFrame {
    private WordList listAE = new WordList();
    private WordList listEY = new WordList();
    private WordList listEH = new WordList();
    private WordList listIY = new WordList();
    private WordList listAY = new WordList();
    private WordList listIH = new WordList();
    private WordList listAA = new WordList();
    private WordList listAO = new WordList();
    private WordList listAW = new WordList();
    private WordList listOW = new WordList();
    private WordList listOY = new WordList();
    private WordList listAH = new WordList();
    private WordList listER = new WordList();
    private WordList listUH = new WordList();
    private WordList listUW = new WordList();
    private WordList fullList = new WordList();
    /**
     * Creates new form RhymingDictionary
     */
    public RhymingDictionary() {
        initComponents();
        try
        {
            File file = new File("Library.txt");
            Scanner in = new Scanner(file);
            String s;
            String p;
            while (in.hasNextLine())
            {
                String line = in.nextLine();
                Scanner lineBreaker = new Scanner(line);
                s = new String(lineBreaker.next());
                PhonemeList a = new PhonemeList();
                while(lineBreaker.hasNext())
                {
                    p = new String(lineBreaker.next());                  
                    a.add(new Phoneme(p));
                }
                fullList.add(new Word(s, a));
            }
        }
        catch (FileNotFoundException e)
        {
            System.out.println("File not found");
        }
    }

    public void printResults(WordList wl)
    {
        int i = 0;
        //String s = "";
        String s;
        String format = "|%1$-30s|%2$-30s|\n";
        outputArea.setText("Results: \n");
        for(Word w : wl)
        {
            s = w.getString();
            //s = s + w.getString() + "\t";
            int size = w.getPhonemes().size();
            String s2 = "";
            for(int j = 0; size > j ;j++)
            {
                s2 = s2 + w.getPhonemes().get(j).getPhoneme();
                if(j!=(size-1))
                {
                    if(w.getPhonemes().get(j).isVowel()||(!w.getPhonemes().get(j).isVowel()&&w.getPhonemes().get(j+1).isVowel()))
                    {
                        s2 = s2 + "-";
                    }
                }                
            }
            //s = s + "\n";
            String out[] = { s, s2 };
            outputArea.append(String.format(format, (Object[]) out));
            i++;
        }
        //outputArea.setText(s);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        perfectRhymeBox = new javax.swing.JCheckBox();
        familyRhymeBox = new javax.swing.JCheckBox();
        additiveRhymeBox = new javax.swing.JCheckBox();
        subtractiveRhymeBox = new javax.swing.JCheckBox();
        assonanceRhymeBox = new javax.swing.JCheckBox();
        halfRhymeBox = new javax.swing.JCheckBox();
        consonanceRhymeBox = new javax.swing.JCheckBox();
        syllableNumberMenu = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jTextField1.setText("Enter Your Word Here");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Rhyming Syllables");

        perfectRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        perfectRhymeBox.setText("Perfect Rhymes");
        perfectRhymeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perfectRhymeBoxActionPerformed(evt);
            }
        });

        familyRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        familyRhymeBox.setText("Family Rhymes");

        additiveRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        additiveRhymeBox.setText("Additive Rhymes");

        subtractiveRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        subtractiveRhymeBox.setText("Subtractive Rhymes");

        assonanceRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        assonanceRhymeBox.setText("Assonance Rhymes");
        assonanceRhymeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assonanceRhymeBoxActionPerformed(evt);
            }
        });

        halfRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        halfRhymeBox.setText("Half-Rhymes");

        consonanceRhymeBox.setBackground(new java.awt.Color(0, 255, 255));
        consonanceRhymeBox.setText("Consonance Rhymes");
        consonanceRhymeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consonanceRhymeBoxActionPerformed(evt);
            }
        });

        syllableNumberMenu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        syllableNumberMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syllableNumberMenuActionPerformed(evt);
            }
        });

        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        outputArea.setColumns(20);
        outputArea.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        outputArea.setRows(5);
        jScrollPane1.setViewportView(outputArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(assonanceRhymeBox)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(syllableNumberMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel8)))
                    .addComponent(consonanceRhymeBox)
                    .addComponent(halfRhymeBox)
                    .addComponent(perfectRhymeBox)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(familyRhymeBox)
                    .addComponent(additiveRhymeBox)
                    .addComponent(subtractiveRhymeBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 864, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(perfectRhymeBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(familyRhymeBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(additiveRhymeBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(subtractiveRhymeBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assonanceRhymeBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(halfRhymeBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(consonanceRhymeBox, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(syllableNumberMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(0, 285, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void perfectRhymeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perfectRhymeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perfectRhymeBoxActionPerformed

    private void assonanceRhymeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assonanceRhymeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assonanceRhymeBoxActionPerformed

    private void consonanceRhymeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consonanceRhymeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_consonanceRhymeBoxActionPerformed

    private void syllableNumberMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syllableNumberMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_syllableNumberMenuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String word = new String(jTextField1.getText());
        Word search = fullList.getWord(word);
        System.out.println("Word found");
        WordList results = new WordList();
        int syl = syllableNumberMenu.getSelectedIndex()+1;
        if (search.getVowelCount()< syl)
        {
            System.out.println("Given word is shorter than specified number of syllables.");
            System.out.println("Number of syllables adjusted to length of word.");
            syl = search.getVowelCount();
        }
        if(perfectRhymeBox.isSelected())
        {
            System.out.println("Finding perfect rhymes.");
            results.addAll(fullList.getPerfectRhymes(search, syl));
            System.out.println("Perfect rhymes found.");
        }
        if(familyRhymeBox.isSelected())
        {
            System.out.println("Finding family rhymes.");
            results.addAll(fullList.getFamilyRhymes(search, syl));
            System.out.println("Family rhymes found.");
        }
        if(additiveRhymeBox.isSelected())
        {
            System.out.println("Finding additive rhymes.");
            results.addAll(fullList.getAdditiveRhymes(search, syl));
            System.out.println("Additive rhymes found.");
        }
        if(subtractiveRhymeBox.isSelected())
        {
            System.out.println("Finding substractive rhymes.");
            results.addAll(fullList.getSubtractiveRhymes(search, syl));
            System.out.println("Subtractive rhymes found.");
        }
        if(assonanceRhymeBox.isSelected())
        {
            System.out.println("Finding assonance rhymes.");
            results.addAll(fullList.getAssonanceRhymes(search, syl));
            System.out.println("Assonance rhymes found.");
        }
        if(halfRhymeBox.isSelected())
        {
            System.out.println("Finding half-rhymes.");
            results.addAll(fullList.getHalfRhymes(search, syl));
            System.out.println("Half-rhymes found.");
        }
        if(consonanceRhymeBox.isSelected())
        {
            System.out.println("Finding consonance rhymes.");
            results.addAll(fullList.getConsonanceRhymes(search, syl));
            System.out.println("Consonance rhymes found.");
        }
        for(Word f : results)
        {
            System.out.print(f.getString()+ " ");
            for(Phoneme c : f.getPhonemes())
            {
                System.out.print("-" + c.getPhoneme());
            }
            System.out.print("\n");
        }
        printResults(results);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RhymingDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RhymingDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RhymingDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RhymingDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RhymingDictionary().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox additiveRhymeBox;
    private javax.swing.JCheckBox assonanceRhymeBox;
    private javax.swing.JCheckBox consonanceRhymeBox;
    private javax.swing.JCheckBox familyRhymeBox;
    private javax.swing.JCheckBox halfRhymeBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea outputArea;
    private javax.swing.JCheckBox perfectRhymeBox;
    private javax.swing.JCheckBox subtractiveRhymeBox;
    private javax.swing.JComboBox syllableNumberMenu;
    // End of variables declaration//GEN-END:variables
}
